name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
             cd /home/ubuntu/hello-api
             git pull origin main

             docker build -t hello-api .

             docker stop hello-api-container || true
             docker rm hello-api-container || true

             docker run -d -p 127.0.0.1:3000:3000 --name hello-api-container hello-api
